language: objective-c
osx_image: xcode7.3
xcode_workspace: SKMopidyDemo/SKMopidyDemo.xcworkspace
xcode_scheme: SKMopidyDemo
xcode_sdk: iphonesimulator
before_install:
before_script:
- git submodule init
- git submodule update

